groups:
  - name: 'main group'
    keywords:
      - 'ампула'
      - 'бентонит'
      - 'бетонит'
      - 'верёвка'
      - 'вольер'
      - 'габа'
      - 'габапентин'
      - 'джут'
      - 'джутовый'
      - 'дралка'
      - 'инъекция'
      - 'когтедерка'
      - 'когтедралка'
      - 'когтеточка'
      - 'консервы'
      - 'корм'
      - 'кот'
      - 'кошачий'
      - 'кошка'
      - 'лежак'
      - 'лежанка'
      - 'лотков'
      - 'лоток'
      - 'мальтпаста'
      - 'мальт-паста'
      - 'молоко'
      - 'паучить'
      - 'паштет'
      - 'пелёнка'
      - 'поводок'
      - 'подстилка'
      - 'подушечка'
      - 'поилка'
      - 'тоннель'
      - 'точилка'
      - 'туннель'
      - 'укол'
      - 'фонтанчик'
      - 'шлейка'
      - 'шприц'
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 1'
    keywords:
      - 'витамин'
      - 'вкусняшка'
      - 'домик'
      - 'еда'
      - 'звенелка'
      - 'игрушка'
      - 'каталка'
      - 'клетка'
      - 'лакомство'
      - 'лекарство'
      - 'мята'
      - 'наполнитель'
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 2'
    keywords:
      - 'подушка'
    include_keywords:
      - 'бесплатно'
      - 'донат'
      - 'плоская'
      - 'лежанка'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'additional group 3'
    keywords:
      - 'переноска'
      - 'миска'
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
      - 'собака'
      - 'собачья'
  - name: 'air conditioner group'
    keywords:
      - 'кондиционер'
      - 'кондей'
      - 'сплитсистема'
      - 'сплит-система'
    exclude_keywords:
      - 'аренда'
      - 'купить'
      - 'шампунь'
      - 'сдаваться'
      - 'сдавать'
      - 'сдать'
      - 'трансфер'
      - 'визаран'
