chats:
  - https://t.me/baraholka_tbi
  - https://t.me/avito_baraholka_tbilisi
  - https://t.me/baraholka_tbilisi
  - https://t.me/otdam_tbilisi
  - https://t.me/tbilisi_obyavleniya
  - https://t.me/Tbilisi_help
  - https://t.me/freegantbilisi
  - https://t.me/Tbilisi_market_bg
  - https://t.me/rabbitsbaraholka

keywords:
  - 'бентонит'
  - 'бетонит'
  - 'веревка'
  - 'габапентин'
  - 'джут'
  - 'джутовая'
  - 'джутовый'
  - 'домик'
  - 'дралка'
  - 'игрушки'
  - 'клетка'
  - 'коврик'
  - 'когтедерка'
  - 'когтедралка'
  - 'когтеточка'
  - 'консервы'
  - 'корм'
  - 'кот'
  - 'кошачий'
  - 'кошачье'
  - 'кошачья'
  - 'кошка'
  - 'кошкам'
  - 'кошке'
  - 'лежак'
  - 'лежанка'
  - 'лекарства'
  - 'лоток'
  - 'лотков'
  - 'мальт-паста'
  - 'миска'
  - 'миски'
  - 'молоко'
  - 'мята'
  - 'наполнитель'
  - 'паучи'
  - 'паштет'
  - 'пеленки'
  - 'перевозка'
  - 'переноска'
  - 'поводок'
  - 'подстилка'
  - 'подушка'
  - 'поилка'
  - 'тоннель'
  - 'точилка'
  - 'туннель'
  - 'фонтанчик'
  - 'шлейка'
  - 'шприцы'
