chats:
  # - https://t.me/+_Pl25IKyOolhNWFi # for testing purposes
  - https://t.me/catebitest01 # for testing purposes
  

developers: "@tk0nik"

keyword_group_1:
  - 'ампула'
  - 'бентонит'
  - 'бетонит'
  - 'верёвка'
  - 'вольер'
  - 'габа'
  - 'габапентин'
  - 'джут'
  - 'джутовый'
  - 'дралка'
  - 'инъекция'
  - 'когтедерка'
  - 'когтедралка'
  - 'когтеточка'
  - 'консервы'
  - 'корм'
  - 'кот'
  - 'кошачий'
  - 'кошка'
  - 'лежак'
  - 'лежанка'
  - 'лотков'
  - 'лоток'
  - 'мальтпаста'
  - 'мальт-паста'
  - 'молоко'
  - 'паучить'
  - 'паштет'
  - 'пелёнка'
  - 'поводок'
  - 'подстилка'
  - 'подушечка'
  - 'поилка'
  - 'тоннель'
  - 'точилка'
  - 'туннель'
  - 'укол'
  - 'фонтанчик'
  - 'шлейка'
  - 'шприц'

keyword_group_2:
  - 'витамин'
  - 'вкусняшка'
  - 'домик'
  - 'еда'
  - 'звенелка'
  - 'игрушка'
  - 'каталка'
  - 'клетка'
  - 'лакомство'
  - 'лекарство'
  - 'мята'
  - 'наполнитель'

keyword_group_3:
  - 'подушка'

keyword_group_4:
  - 'переноска'
  - 'миска'

filter_keyword_group_2:
  - животное
  - кошачий
  - кошка
  - кот

filter_keyword_group_3:
  - бесплатно
  - донат
  - плоская
  - лежанка
  - кошачий
  - кошка
  - кот

filter_keyword_group_4:
  - животное
  - кошачий
  - кошка
  - кот
  - собака
  - собачья

