chats:
  - https://t.me/catebitest01
  - https://t.me/catebitest02

keywords:
  - 'ампула'
  - 'бентонит'
  - 'бетонит'
  - 'верёвка'
  - 'витамин'
  - 'вкусняшка'
  - 'вольер'
  - 'габа'
  - 'габапентин'
  - 'джут'
  - 'джутовый'
  - 'домик'
  - 'дралка'
  - 'еда'
  - 'звенелка'
  - 'игрушка'
  - 'инъекция'
  - 'каталка'
  - 'клетка'
  - 'когтедерка'
  - 'когтедралка'
  - 'когтеточка'
  - 'консервы'
  - 'корм'
  - 'кот'
  - 'кошачий'
  - 'кошка'
  - 'лакомство'
  - 'лежак'
  - 'лежанка'
  - 'лекарство'
  - 'лотков'
  - 'лоток'
  - 'мальтпаста'
  - 'мальт-паста'
  - 'миска'
  - 'молоко'
  - 'мята'
  - 'наполнитель'
  - 'паучить'
  - 'паштет'
  - 'пелёнка'
  - 'переноска'
  - 'поводок'
  - 'подстилка'
  - 'подушечка'
  - 'подушка'
  - 'поилка'
  - 'тоннель'
  - 'точилка'
  - 'туннель'
  - 'укол'
  - 'фонтанчик'
  - 'шлейка'
  - 'шприц'
