groups:
  - name: 'main group'
    keywords:
      - 'ампула'
      - 'бентонит'
      - 'бетонит'
      - 'витамин'
      - 'вкусняшка'
      - 'вольер'
      - 'габа'
      - 'габапентин'
      - 'джут'
      - 'джутовый'
      - 'домик'
      - 'дралка'
      - 'игрушка'
      - 'инъекция'
      - 'клетка'
      - 'когтедерка'
      - 'когтедралка'
      - 'когтеточка'
      - 'консервы'
      - 'корм'
      - 'кот'
      - 'кошачий'
      - 'кошка'
      - 'лакомство'
      - 'лежак'
      - 'лежанка'
      - 'лотков'
      - 'лоток'
      - 'мальтпаста'
      - 'мальт-паста'
      - 'мята'
      - 'молоко'
      - 'наполнитель'
      - 'паштет'
      - 'пелёнка'
      - 'поводок'
      - 'подстилка'
      - 'поилка'
      - 'тоннель'
      - 'туннель'
      - 'укол'
      - 'фонтанчик'
      - 'шлейка'
      - 'шприц'
    include_keywords:
      - 'животное'
      - 'кошачий'
      - 'кошка'
      - 'кот'
  - name: 'carrier'
    keywords:
      - 'переноска'
