chats:
  - https://t.me/catebitest01
  - https://t.me/catebitest02

keywords:
  - 'ампулы'
  - 'бентонит'
  - 'бетонит'
  - 'веревка'
  - 'витамины'
  - 'вкусняшка'
  - 'вкусняшки'
  - 'вольер'
  - 'габа'
  - 'габапентин'
  - 'джут'
  - 'джутовая'
  - 'джутовый'
  - 'домик'
  - 'дралка'
  - 'еда'
  - 'звенелка'
  - 'игрушка'
  - 'игрушки'
  - 'инъекции'
  - 'каталка'
  - 'клетка'
  - 'когтедерка'
  - 'когтедралка'
  - 'когтеточка'
  - 'консервы'
  - 'корм'
  - 'кот'
  - 'кошачий'
  - 'кошачье'
  - 'кошачья'
  - 'кошка'
  - 'кошкам'
  - 'кошке'
  - 'кошки'
  - 'лакомства'
  - 'лакомство'
  - 'лежак'
  - 'лежанка'
  - 'лекарства'
  - 'лотков'
  - 'лоток'
  - 'мальт-паст'
  - 'миска'
  - 'миски'
  - 'молоко'
  - 'мята'
  - 'наполнитель'
  - 'паучи'
  - 'паштет'
  - 'пеленки'
  - 'переноска'
  - 'поводок'
  - 'подстилка'
  - 'подушечки'
  - 'подушка'
  - 'поилка'
  - 'тоннель'
  - 'точилка'
  - 'туннель'
  - 'уколы'
  - 'фонтанчик'
  - 'шлейка'
  - 'шприцы'