chats:
  - https://t.me/catebitest01 # for testing purposes
  - https://t.me/catebitest02 # for testing purposes
  - https://t.me/baraholka_tbi
  - https://t.me/avito_baraholka_tbilisi
  - https://t.me/baraholka_tbilisi
  - https://t.me/otdam_tbilisi
  - https://t.me/tbilisi_obyavleniya
  - https://t.me/Tbilisi_help
  - https://t.me/freegantbilisi
  - https://t.me/Tbilisi_market_bg
  - https://t.me/rabbitsbaraholka
  - https://t.me/tbilisi_otdam_darom
  - https://t.me/expatstbilisi
  - https://t.me/tbilisi_rus
  - https://t.me/tbilisi_360
  - https://t.me/tbilisio
  - https://t.me/gryzia_chat_ads
  - https://t.me/tbilisi_baraxolka
  - https://t.me/tbilisiw
  - https://t.me/tbilisi_avito
  - https://t.me/Georgia_Avito
  - https://t.me/barter_ge

sys_logging:
  developers: "@lejafo"
  topic_id: 2693


keyword_group_1:
  - 'ампула'
  - 'бентонит'
  - 'бетонит'
  - 'верёвка'
  - 'вольер'
  - 'габа'
  - 'габапентин'
  - 'джут'
  - 'джутовый'
  - 'дралка'
  - 'инъекция'
  - 'когтедерка'
  - 'когтедралка'
  - 'когтеточка'
  - 'консервы'
  - 'корм'
  - 'кот'
  - 'кошачий'
  - 'кошка'
  - 'лежак'
  - 'лежанка'
  - 'лотков'
  - 'лоток'
  - 'мальтпаста'
  - 'мальт-паста'
  - 'молоко'
  - 'паучить'
  - 'паштет'
  - 'пелёнка'
  - 'поводок'
  - 'подстилка'
  - 'подушечка'
  - 'поилка'
  - 'тоннель'
  - 'точилка'
  - 'туннель'
  - 'укол'
  - 'фонтанчик'
  - 'шлейка'
  - 'шприц'

keyword_group_2:
  - 'витамин'
  - 'вкусняшка'
  - 'домик'
  - 'еда'
  - 'звенелка'
  - 'игрушка'
  - 'каталка'
  - 'клетка'
  - 'лакомство'
  - 'лекарство'
  - 'мята'
  - 'наполнитель'

keyword_group_3:
  - 'подушка'

keyword_group_4:
  - 'переноска'
  - 'миска'

filter_keyword_group_2:
  - животное
  - кошачий
  - кошка
  - кот

filter_keyword_group_3:
  - бесплатно
  - донат
  - плоская
  - лежанка
  - кошачий
  - кошка
  - кот

filter_keyword_group_4:
  - животное
  - кошачий
  - кошка
  - кот
  - собака
  - собачья

